version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:


  # app:
  #   build: .
  #   container_name: node_app
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - .:/app
  #   networks:
  #     db:

networks:
  db:
